{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "minikube2",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/minikube2",
    "uid": "3cce439f-1d65-11e8-9af1-08002727c021",
    "resourceVersion": "6695",
    "generation": 2,
    "creationTimestamp": "2018-03-01T15:28:48Z",
    "labels": {
      "run": "minikube2"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 4,
    "selector": {
      "matchLabels": {
        "run": "minikube2"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "run": "minikube2"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "minikube2",
            "image": "geoserver:v2",
            "ports": [
              {
                "containerPort": 3004,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    }
  },
  "status": {
    "observedGeneration": 2,
    "replicas": 4,
    "updatedReplicas": 4,
    "readyReplicas": 4,
    "availableReplicas": 4,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-03-01T16:32:58Z",
        "lastTransitionTime": "2018-03-01T16:32:58Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}
